version: '3.1'

services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interview
    ports:
      - 11500:5432
